name: Upload Python Package To Test Pypi
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build package
      run: |
        for each in $(find "${GITHUB_WORKSPACE}" -maxdepth 1 -mindepth 1 -type d -name "*sdk*")
        do
          cd "${each}" || exit 1
          python setup.py bdist_wheel
          cp dist/*.whl "${GITHUB_WORKSPACE}"
        done
      shell: bash
    - name: Publish package
      run: |
        echo "[testpypi]" >> "${HOME}/.pypirc"
        echo "username = __token__" >> "${HOME}/.pypirc"
        echo "password = ${TEST_PYPI_API_TOKEN}" >> "${HOME}/.pypirc"
        cd "${GITHUB_WORKSPACE}" || exit 1
        twine upload --repository testpypi ./*.whl --skip-existing --verbose
      env:
        TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
